### PR TITLE
Remove astro-sdk ingestion

### PR DESCRIPTION
**Pull request by sunank200**
- Removed the astro-sdk ingestion as per suggestion with Steven

More details at: [slack thread](https://astronomer.slack.com/archives/C06CGUXM0LE/p1704489285398289)

### CODE REVIEW

**Review by davidgxue — APPROVED** [review]
Thank you Ankit for the quick turnaround! And just to confirm, we are leaving these commented out instead of deleting them in case we want to use them in the future, right? Perhaps in the future, we want to re-ingest these after adding some processing/data cleaning steps. I don't feel strongly about this either way, up to you and the team.

**Review by Lee-W — APPROVED** [review]
I would also suggest deleting these lines as well, but not a blocker for this PR

**Review by pankajastro — COMMENTED** [review]
somehow the slack link you added is not accessible to me.

**Comment by sunank200** [comment]
> somehow the slack link you added is not accessible to me.

@pankajastro you should be able to see now.

**Comment by sunank200** [comment]
> Thank you Ankit for the quick turnaround! And just to confirm, we are leaving these commented out instead of deleting them in case we want to use them in the future, right? Perhaps in the future, we want to re-ingest these after adding some processing/data cleaning steps. I don't feel strongly about this either way, up to you and the team.

Yes removed it for now. cc: @Lee-W @davidgxue

**Pull request merged**
