### PR TITLE
Special case for code samples source URL display

### LINKED ISSUE #17: Code samples from Learn Docs are shown as sources with a non-existent link
When Ask Astro shows a Source that is from the code-samples folder (retrieved from `https://github.com/astronomer/docs/blob/main/code-samples/dags`) in the Astronomer Docs repo it shows a link to the docs.astronomer page like this `https://docs.astronomer.io/code-samples/dags/...`. These code samples are embedded in other docs on the page and not accessible through that link. 

Solution proposed in #16 : 
create an extra case for the URL prefix and link to the DAG code in the GitHub repo.

### PR DESCRIPTION
**Pull request by TJaniF**
Resolves #17 

The code-samples from the docs repo are not accessible via the main docs page, only in the public repo. I attempted to add a case in to consider that. The main word in that sentence is attempted, I don't know java script and this was just trying to find a pattern somewhere that looked like it might fit 👀

### CODE REVIEW

**Comment by mpgreg** [comment]
I was originally thinking that we want to get the correct URL during ingest but now I think this is better.  Ingest creates the 'docLink' based on the original github location.  Recreating the link for presentation layer here in the app is the correct choice IMO.

**Comment by sunank200** [comment]
@TJaniF can you rebase this PR, please?

**Review by sunank200 — COMMENTED** [review]
Can you rebase this PR please?

**Review by pankajastro — APPROVED** [review]

**Comment by TJaniF** [comment]
> Can you rebase this PR please?

I merged in the changes from main :)

**Review by Lee-W — APPROVED** [review]

**Comment by pankajastro** [comment]
@sunank200 shall we include this in the coming release?

**Comment by sunank200** [comment]
> @sunank200 shall we include this in the coming release?

@pankajastro we are anyways ingesting docs from webpages now: https://github.com/astronomer/ask-astro/pull/238

**Review by sunank200 — CHANGES_REQUESTED** [review]
https://github.com/astronomer/ask-astro/pull/16#issuecomment-1871020958

**Comment by TJaniF** [comment]
@sunank200 Thank you! Looking at #238 I think this PR (#16) is obsolete after #238 is merged, since it is only relevant for github URLs of code-samples. Closing. :)

**Pull request closed without merging**
