### PR TITLE
Add basic local dev script

### PR DESCRIPTION
**Pull request by pankajastro**
closes: #30 

Add a simple script and document to run the API server, UI and generate env template for API server

### CODE REVIEW

**Comment by Lee-W** [comment]
in addition to required env vars, we'll also need to setup `gcp.json` and GOOGLE_APPLICATION_CREDENTIALS
https://cloud.google.com/docs/authentication/application-default-credentials
cc @sunank200

**Review by sunank200 — COMMENTED** [review]
Don't we review dockerfile with env here? And how does one set env? Another thing to consider is a local dev story for the slack app. You can use something like this to forward the port for slackbot: https://ngrok.com/docs/secure-tunnels/non-local/#:~:text=Forwarding%20to%20servers%20on%20a,network%20address%20and%20port%20instead.

**Comment by pankajastro** [comment]
> in addition to required env vars, we'll also need to setup `gcp.json` and GOOGLE_APPLICATION_CREDENTIALS https://cloud.google.com/docs/authentication/application-default-credentials cc @sunank200

Yes, But don't want to checkin the copy command so added a comment in dockerfile also added a way to generate template for env require in API

**Comment by pankajastro** [comment]
> Don't we review dockerfile with env here? And how does one set env? Another thing to consider is a local dev story for the slack app. You can use something like this to forward the port for slackbot: https://ngrok.com/docs/secure-tunnels/non-local/#:~:text=Forwarding%20to%20servers%20on%20a,network%20address%20and%20port%20instead.

Added way to generate a template for env. slack part will be addressed https://github.com/astronomer/ask-astro/pull/42

**Comment by sunank200** [comment]
Lets not merge this PR before approval please @pankajastro

**Comment by sunank200** [comment]
This PR has better approach of local dev story: https://github.com/astronomer/ask-astro/pull/42

**Pull request merged**
