### PR TITLE
refactor(airflow): refactor extract_astro_blogs method

### PR DESCRIPTION
**Pull request by Lee-W**
When parsing links, parse the article tag to get the date to filter. Break the loop if any dates are filtered in an iteration.

closes: #116

### CODE REVIEW

**Review by phanikumv — APPROVED** [review]

**Review by pankajastro — APPROVED** [review]

**Review by sunank200 — COMMENTED** [review]
@Lee-W how have you tested this? Requesting you to run the DAG once and test this change

**Comment by Lee-W** [comment]
I ran these function and compare the results. Let me run the tests on DAG as well

**Comment by Lee-W** [comment]
圖片

**Comment by sunank200** [comment]
> @sunank200 I've tested with local DAGs
> 
> 圖片

@Lee-W For each of these changes in ingestion. We need to do the following:

**Review by sunank200 — CHANGES_REQUESTED** [review]
Blocking this change till this is tested by @vatsrahul1001

**Comment by Lee-W** [comment]
> Ingest the data to the dev database with a change in ingestion code.

May I know where is the dev database and dev airflow environment we can ingest? also what is the change you mentioned? do you mean the code change in this PR?

**Comment by mpgreg** [comment]
One thing to think about here...  The current code uses source-specific extract.  The extract function is specific to astro blogs.  Alternatively the code at https://github.com/mpgreg/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-html.py has one extract function which scrapes any webpage given some parameters.  I *think* it will generalize pretty well but have not really tested.  The main problem for astro blogs is there is no generalizable way to specify a cutoff date.

Perhaps that is okay.  We can check with Juliana if there is some specific reason we don't want to include older blogs.

**Comment by sunank200** [comment]
> > One thing to think about here... The current code uses source-specific extract. The extract function is specific to astro blogs. Alternatively the code at https://github.com/mpgreg/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load-html.py has one extract function which scrapes any webpage given some parameters. I _think_ it will generalize pretty well but have not really tested. The main problem for astro blogs is there is no generalizable way to specify a cutoff date.
> > Perhaps that is okay. We can check with Juliana if there is some specific reason we don't want to include older blogs.
> 
> I guess the reason behind it might be the same as what we did on StackOverflow? But I'm ok with it as well. I'll hold the work on this PR. Till we have a decision

@Lee-W can you setup a call for this please and lets have a decision on this? After that this change should be tested with fresh ingestion on dev database.

**Comment by Lee-W** [comment]
as discussed earlier, we still need this cutoff date. will proceeded testing on this one

**Comment by Lee-W** [comment]
I changed the host and pointed to the dev WEAVIATE. @vatsrahul1001 Could you please help with the testing? Thanks!

**Comment by Lee-W** [comment]
@vatsrahul1001 We no longer need to test it on cloud. Thanks!

@sunank200 I've tested it and send you the result. Could you please take a look? Thanks!

**Review by sunank200 — APPROVED** [review]
LGTM

**Pull request merged**
