### PR TITLE
Add contact us link to AI-generated responses

### PR DESCRIPTION
**Pull request by jlaneve**

### CODE REVIEW

**Review by pgagnon — COMMENTED** [review]
Wdyt about merging this with the "AI-generated content may be incorrect" line?

**Comment by jlaneve** [comment]
> Wdyt about merging this with the "AI-generated content may be incorrect" line?

I was thinking about that, but we want this link to be more prevalent. The "AI-generated content ..." line is hidden under a hover today.

**Review by sunank200 — APPROVED** [review]

**Comment by pankajastro** [comment]
Look like `Cloudflare Pages` job has stuck

**Comment by jlaneve** [comment]
> Look like `Cloudflare Pages` job has stuck

Cloudflare's having an outage unfortunately - https://www.cloudflarestatus.com

**Review by pankajastro — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Pull request merged**
