### PR TITLE
Setup readthedocs and CI job for checking documentation building

### LINKED ISSUE #94: Setup readthedocs
**Please describe the feature you'd like to see**
build docs and publish to readthedocs

**Describe the solution you'd like**

**Are there any alternatives to this feature?**

**Additional context**

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

### PR DESCRIPTION
**Pull request by Lee-W**
* circleci
    * add build-docs step for check doc building process
    * use python 3.11 for consistency
* readthedocs
    * add readthedocs config

close #94

### CODE REVIEW

**Comment by Lee-W** [comment]
According to [build](https://docs.readthedocs.io/en/stable/builds.html), it seems as if we already connect to the readthedocs, it will build for us automatically. @sunank200 Do you know who have the access to read the dashboard so that we can check? Thanks!

**Comment by sunank200** [comment]
> According to [build](https://docs.readthedocs.io/en/stable/builds.html), it seems as if we already connect to the readthedocs, it will build for us automatically. @sunank200 Do you know who have the access to read the dashboard so that we can check? Thanks!

Do we need to build this for readthedocs now?

**Comment by Lee-W** [comment]
not really, more like a nice to have and GitHub pages would be another option that's easier to setup

**Comment by sunank200** [comment]
We should use GitHub Pages instead here @Lee-W

**Review by sunank200 — COMMENTED** [review]
We should use GitHub Pages instead here @Lee-W

**Review by pankajastro — APPROVED** [review]
LGTM

**Comment by pankajastro** [comment]
@sunank200 do you want to hold for https://github.com/astronomer/ask-astro/pull/93#pullrequestreview-1722356502 or we should merge it or wdyt?

**Comment by pankajastro** [comment]
> @sunank200 do you want to hold for [#93 (review)](https://github.com/astronomer/ask-astro/pull/93#pullrequestreview-1722356502) or we should merge it or wdyt?

created GH issue https://github.com/astronomer/ask-astro/issues/122 to track it

**Pull request merged**
